### ISSUE TITLE
Incorrect Format when importing from Postman

### ISSUE THREAD

**Issue by Prince2k3** [luckymarmot/Paw-PostmanImporter#16]
![screen shot 2016-07-28 at 10 34 28 am](https://cloud.githubusercontent.com/assets/2805285/17218894/f6852e56-54ae-11e6-9917-ee74765da9d5.png)

When importing from postman, I noticed the url format is incorrect.

I am getting '~1' instead of '/'

Also Postman uses variables and I'm not sure where to set that in Paw 3

**Comment by JonathanMontane** [comment]
@Prince2k3 actually, what you see there is not the url, but a reference to an environment variable, named `x-postman/{{URL}}~1/rest~1model~1atg~1...` that you can find in the environments menu. I know the name sucks, and I'm working on improving it, but there are reasons behind the naming convention that I can maybe explain a bit more.

We are currently working on a cool library that allows one to convert any file from CURL, Postman, RAML, Swagger, etc. into one another. Most of these formats use different ways to represent references to other data. For instance, Postman uses what could be called Late Resolution References, where the value of a variable can only be known at runtime by replacing the different references with their corresponding values, recursively. This, in itself is fine, but it does not really play ball with other description formats, such as Swagger, which requires every references to be a JSON pointer. So we did a "hack", and transformed postman strings that contained late refs into JSON pointers, so that we could transform Postman files into Swagger files, or RAML files, etc. nicely. And in a JSON Pointer, `\` has a special meaning, which implicates that other backslashes are to be escaped using a scheme defined in its RFC.

Anyway, it's not super nice, but we should roll out a cool Dynamic Value next week to help users have a better experience when coming from postman.

Thank you for your contribution!

**Comment by Prince2k3** [comment]
So would need to go to each of those variables and give the correct values?

**Comment by JonathanMontane** [comment]
At the moment, yes, unfortunately, but in theory, the variables that were in the environnents in Postman should be imported correctly, if you did an export from the settings panel in Postman. If you did an export of a collection only, we can't have the environment variables, as they are not stored in the generated files from Postman.

Sorry for the inconvenience, the dynamic value we'll roll out next week should make it nicer for postman users, as it will try to find the corresponding values and generate the value as Postman does it.

**Comment by Prince2k3** [comment]
That makes sense. I wait till the next update then.

**Comment by JonathanMontane** [comment]
Fixed in release v2.2.3
