### ISSUE TITLE
Handle dynamic values

### ISSUE THREAD

**Issue by jenanwise** [luckymarmot/Paw-PostmanImporter#3]
Postman exports dynamic environment values in strings like this:

```json
...
"url": "{{API_ROOT}}/v1/foo/bar"
...
```

As far as I can tell, there isn't currently a documented way to parse those and turn them into dynamic values. I see the existence of `com.luckymarmot.EnvironmentVariableDynamicValue` but no docs yet on how to use it :grin:. Am I on the right track?

**Comment by cholick** [comment]
Just noting that this is an issue for me as well. My postman files have 2-5 dynamic values per request, so any imported request requires extensive manual edits.

**Comment by KonanA** [comment]
I am also struggling to import postman dynamic variables. Is it possible to import dynamic variables? If not - any plans to implement this?

**Comment by hishnash** [comment]
Not at the moment however it could be added, we would need to set up a mapping from postman dynamic variables types to Paw dynamic values. Would be helpful if you have some example files to share I will have a look if i can create a branch to test this out.

**Comment by KonanA** [comment]
I am trying to import the following:
 - https://github.com/ryantischer/CiscoAPIC_Postman/blob/master/BasicAPIC.json.postman_collection
 - https://github.com/ryantischer/CiscoAPIC_Postman/blob/master/ChicagoLab.postman_environment

Tnx!

**Comment by hishnash** [comment]
What you be your expected behaviors:
that all {{MYVARNAME}} are created as environment variable with no value set? And always point to this from all requests? 

Due to sandboxing at the moment it is trick for us to open both files at once. A solution would be to have 2 importers. One that does the above, creates environment variables and points all references in the imported postman file and another that imports the environment variable values, also creating any new environment variables that are needed.

I know this is a pain, needing to import the two files separately but without changes to the ObjectiveC file opening process (such that you can select multiple files at once) I think this would be the best option.

Does this make sense you did you have a different idea?

**Comment by KonanA** [comment]
Expected behaviour:
Step 1:
Import postman environment in order to get all dynamic variables into Paw

Step 2:
Import postman collection where import automatically replaces postman dynamic variables {{MYVARNAME}} with Paw dynamic variables. If variable doesn't exist in environment (i.e.: postman variable can not be converted into paw variable) the import script shows a warning and leaves the variable in postman format, which can be changed into paw format later when all missing variables are added. 

I don't mind using two step importer as long as I don't have to manually update variables from postman format to Paw format ...

**Comment by hishnash** [comment]
Ok i can build a prototype for this. In the files you sent are there any other dynamic values than those environment variables?

**Comment by KonanA** [comment]
As far as I know only env. variables are used in collection.

**Comment by hishnash** [comment]
@KonanA @cholick @jenanwise Please update your Postman importer to v1.1.1 we know support environment variable references. 

Remember you can import an existing post man environment with this. https://luckymarmot.com/paw/extensions/PostmanEnvironmentImporter.

As a quite summary of what is know supported: #4 

Variables will point to Environment Domain "Postman (Imported)" this can be renamed after import safely without losing reference. 

Supported Locations for Environment Variables?\:
* [x] path
* [x] JSON body supports both key and value
* [x] Plain text body supports everywhere
* [x] Form URL and Multipart supports value only
* [x] Headers Key and value
* [x] url Params

:warning: Unlike postman this will add **ALL** {{ ... }} to the environment.

**Comment by KonanA** [comment]
I did a quick test (import CiscoAPIC_postman env/collection) and it seems that translating postman variables to Paw variables is working now. Thanks for a quick fix!!
